### ISSUE TITLE
Dash Icon Request

### ISSUE THREAD

**Issue by alleyvandal** [WordPress/dashicons#273]
HI,
Could you please add some folder icons? I am using asgaros forum WordPress plugin and I want to add some open and closed folder icons to the boards. Thank you.

**Comment by habib919000** [comment]
Closed Folder Dash Icon
![screenshot_1](https://user-images.githubusercontent.com/32449876/37382372-bd6b77a0-276c-11e8-91c0-81bdde0163ba.png)

**Comment by Zodiac1978** [comment]
The category icon is looking like your folder icon, maybe this can be used:
https://developer.wordpress.org/resource/dashicons/#category

But there is no open folder icon.

You could use portfolio as a replacement:
https://developer.wordpress.org/resource/dashicons/#portfolio

But I agree that a specific open folder icon would be great.

**Comment by field2** [comment]
It's kind of tough to do this, since the original icon was not intended as a folder that could be opened, but this should work:

![Screen Shot 2020-03-26 at 1 33 38 PM](https://user-images.githubusercontent.com/1656980/77677721-76e09b00-6f66-11ea-82e0-636e9643213e.png)
![Screen Shot 2020-03-26 at 1 33 31 PM](https://user-images.githubusercontent.com/1656980/77677722-76e09b00-6f66-11ea-84ff-40220ae40bc0.png)
[open-folder.svg.zip](https://github.com/WordPress/dashicons/files/4388825/open-folder.svg.zip)

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
