### ISSUE TITLE
New icon request: Cloths/clothing

### ISSUE THREAD

**Issue by geoclaps** [WordPress/dashicons#301]
As the subject describes.

**Comment by Zodiac1978** [comment]
What would be the need of this icon in the WordPress admin area?

**Comment by geoclaps** [comment]
Never knew this would be bumped 2 years later :)

Well, at the time, I was creating a website from scratch wich had a custom options page for managing products (clothing especially) but none of the standard dashicons has got an icon wich is related to this.

**Comment by Zodiac1978** [comment]
> Never knew this would be bumped 2 years later :)

I'm trying to clean a little bit up here and yes, there are really old issues here ... sorry for the delay.

The problem is, the Dashicons have one goal, to serve an iconset for the WordPress admin area. There are not here to solve every possible plugin or theme purpose. Therefore I think clothing is not really in the scope of this iconset. 

There are iconsets (for example Font Awesome: https://fontawesome.com/icons?d=gallery&q=clothing) which are having icons for clothing. I think these are a better match in this case. Because if we try to cover every possible usage, then we will end up with a **huge** iconset.

Unfortunately this is the reason why I will close this issue for now. Thanks for your understanding!

**Comment by geoclaps** [comment]
No problem. Cheers.
