### ISSUE TITLE
Font awesome icons integration request

### ISSUE THREAD

**Issue by JustinyAhin** [WordPress/dashicons#338]
In order to provide users with all or almost all the icons they need, you may consider integrating more complete icon libraries as Font Awesome to WP Dashicon feature

**Comment by cyberalien** [comment]
I suggest a better solution: support for Iconify: https://iconify.design/

Its an open source SVG framework that is designed to replace glyph fonts. It loads only icons used on pages instead of entire fonts, so designers can use Dashicons, FontAwesome, Material Design Icons and many other icon sets on same page without loading massive fonts.

**Comment by Zodiac1978** [comment]
@JustinyAhin Dashicons have a unique goal. They are used for the WordPress admin area. They are not designed to justify everyone's needs. If Font Awesome solves your problem there are many ways to include them.

@cyberalien This is an interesting concept, but it is an external service which would create many potential problems. What happens in intranets? What is the privacy policy of this service? What happens if the service breaks down? Serving these small set of icons locally is not flexible, but much more reliable.

**Comment by cyberalien** [comment]
@Zodiac1978 Intranets, break downs are concerns. API is open source, so anyone can setup their own local version instead of relying on third party service. API is available as Node.js and PHP, allowing choice of hosting platform.

As for privacy policy, I do need to make a page for it. Policy (it will stay that way in future) is that nothing is tracked. There is a cookie that is set by Cloudflare, however API doesn't set any cookies and doesn't do any tracking. I'm in process of full rewrite of website to reflect changes that happened in last year since project went live, new documentation and policy will be part of it.

I am currently working on icon finder, that should make it easy to add icon picker to any software. That could be useful for WP theme builders, menu management and so on. The only downside is it currently relies on my API because search engine is not part of public API packages, but that can be solved.

Additionally icons are available as NPM packages. Icons can be bundled and served as static resource, making it easy to include when shipping software (WP, theme or anything else). Tools for managing custom icon sets are also available.

It might be possible to integrate API into WP directly, though that would greatly increase package size (API is tiny, but currently icons bundle is about 108mb). There could be many workarounds for that, such as loading icon packages on demand from third party API or bundling only icons used by core, plugins and themes.
