### ISSUE TITLE
Preserve current trash, undo, redo icons

### ISSUE THREAD

**Issue by desrosj** [WordPress/dashicons#352]
In WordPress Core today, the trash, undo, and redo icons are different than they are currently in this repo. They were purposefully redesigned (which is great!) but the new versions have replaced the old ones entirely. 

The current icon designs should be preserved at their current locations. The result of the redesign is that any site using these icons will automatically receive the new design, which may not be desired.

I propose adding back the old icons and moving the new ones to new Unicode locations as “-alt” icons.

**Comment by jasmussen** [comment]
Thank you for all the help with #350, and thank you for highlighting this change and creating this ticket. 

The undo/redo and trash icons feature prominently in the Gutenberg editor, and as part of creating a coherent visual look for the top editor bar, these icons were revisited. This is quite a while ago, I'm sure there are historical traces of it in chat or in this repo, I do recall chatting with @field2 about it. The old icons were fine, but next to the new unified (+) Add Block icon, these new icons visually fit better.

For that reason, I consider these icons to simply have been redesigned, and they should keep their 
locations and unicode IDs. This is similar to when any other design is updated — like when Instagram updates their logo, we replace the old one.

Additionally, I don't see great value in keeping the duplicates around when they convey the same and are simply old versions of the same, rather than _alternate_ versions of the same. Take the arrow with stem and alternate arrows that look more like chevrons — these icons are visually compatible and it makes sense for them to coexist and be available for usage. 

To put it differently, keeping an old design around does not feel like maintaining backwards compatibility to me. The icons for undo/redo/trash are still there, they still convey the same meaning, the will still work in a drop-in manner for anyone who adopt the new icon font. They just received a visual refresh. 

In fact I would love for us to be able to also revisit and refresh other dashicons, and not have to keep a version history of every past version around for that ride. In light of [discussions here](https://github.com/WordPress/gutenberg/issues/9647#issuecomment-456738147), this might be especially relevant.

---

The above is my strong opinion, but it is not strongly held. I can absolutely be swayed by good arguments to the contrary. I would suggest that if we are to duplicate the undo/redo and trash icons, then we keep the new designs as they are, and make the old icons receive the `-alt` suffix. That way users who prefer that older look can choose them intentionally. 

On the other hand if we change the new icons to be the -alt versions, we'll need to refactor the WordPress block editor to point to those instead, as it relies on the icon _names_ (not the unicode addresses).

**Comment by desrosj** [comment]
This was fixed in #350.
