### ISSUE TITLE
Tide icon: paths are not correct

### ISSUE THREAD

**Issue by davewhitley** [WordPress/dashicons#370]
The svg that was provided in https://github.com/WordPress/dashicons/issues/248#issuecomment-350778020is different than the svg that exists in this repo. It seems that the paths somehow got mangled when the icon was added to the library.

**Provided icon**:
![Screen Shot 2019-07-30 at 2 41 48 PM](https://user-images.githubusercontent.com/618551/62160236-19ae2000-b2d9-11e9-8ffc-f52ef19610e5.png)

**Current icon**:
![Screen Shot 2019-07-30 at 2 41 38 PM](https://user-images.githubusercontent.com/618551/62160211-1024b800-b2d9-11e9-9873-1962df8f3e7b.png)

Notice how the top slope is not smooth in the current svg. It looks like the paths and anchor points could be cleaner.

hat tip @anyssa

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77773161-95569d00-701f-11ea-99be-01eaaaeb4718.png)

[tide.svg.zip](https://github.com/WordPress/dashicons/files/4394459/tide.svg.zip)
I cleaned up the curve a bit. This may be happenning in the buuild process, since I sorta remember doing this before.

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
