### ISSUE TITLE
Localized icons and RTL

### ISSUE THREAD

**Issue by TheTracyL** [WordPress/dashicons#62]
Load alternative icons based on language installed.

Flip icons horizontally if RTL.

**Comment by fduraibi** [comment]
That can be done easily by utilizing the mirror feature of the unicode characters. Some glyph like `<`, `(`, `{` ....etc has a mirror property so when the interface is flipped to RTL the browser automatically picks the mirrored version of these glyph which in this case will be  `>`, `)`, `}` ....etc

So any icon that needs flipping to work with RTL should be assigned a code that has the mirror property and assign its flipped version the matching code so everything will work without any extra coding.

And also for other icons avoid using these mirrors locations otherwise switching to RTL will replace the icon with something different (see here for an example of expected issues https://github.com/RocketChat/Rocket.Chat/issues/1577)

For more info read:  http://www.unicode.org/Public/UCD/latest/ucd/BidiMirroring.txt
