### ISSUE TITLE
Varnish Icon

### ISSUE THREAD

**Issue by blindpet** [WordPress/dashicons#88]
I had a Varnish icon made, there will be an alternative too with body but I think this looks best. It is svg in zip format to please github.
[varnish vector.zip](https://github.com/WordPress/dashicons/files/85174/varnish.vector.zip)

**Comment by blindpet** [comment]
Here is an updated zip with both icons

[varnish vector.zip](https://github.com/WordPress/dashicons/files/85211/varnish.vector.zip)

**Comment by melchoyce** [comment]
Hey @blindpet, can you speak a little to why you'd like this icon included and what you see it being used for in the WordPress admin?

**Comment by blindpet** [comment]
Varnish is used to make WordPress very fast, it will help users identify the correct area for a plugin that uses Varnish to manage the cache - a visual cue is almost always superior to a textual one. This is especially important with more plugins using the admin bar area for quick and convenient access to help users manage their WordPress installations without confusion.

There are plenty of Varnish plugins in the official repository and WPEngine and other hosting providers use it. Almost all of them use the Admin top bar as well.

Originally I thought using f463 would suffice but that is already in the top bar and could cause unnecessary confusion.

**Comment by melchoyce** [comment]
Thanks. Looking at your vectors, they're very large and detailed, which won't work for a Dashicon. Dashicons need to display within a 20x20 pixel grid. I don't think the Varnish rabbit will be able to work at that size (though the three dots in this logo might: https://www.varnish-software.com/branding)

Please check out the style guide for some tips on making a new Dashicon: https://make.wordpress.org/design/dashicons-style-guide/ Especially Ben's video walkthrough.

Design aside, I don't think it's a good candidate for inclusion in Dashicons. We're trying to avoid adding any new social or brand icons. If you made an icon, though, you could offer it to Varnish plugins since plugins can include their own svg icons.

**Comment by field2** [comment]
Nice icon! But yeah, what @melchoyce said.

**Comment by blindpet** [comment]
Can plugin authors add unofficial dashicons in the top admin bar though (not the sidebar)?

**Comment by melchoyce** [comment]
I believe plugin authors can add icons anywhere.
